=begin
#Figshare API

#Figshare apiv2. Using Swagger 2.0

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

# Common files
require 'swagger_client/api_client'
require 'swagger_client/api_error'
require 'swagger_client/version'
require 'swagger_client/configuration'

# Models
require 'swagger_client/models/account'
require 'swagger_client/models/account_create'
require 'swagger_client/models/account_group_roles'
require 'swagger_client/models/account_group_roles_create'
require 'swagger_client/models/account_update'
require 'swagger_client/models/article'
require 'swagger_client/models/article_confidentiality'
require 'swagger_client/models/article_create'
require 'swagger_client/models/article_doi'
require 'swagger_client/models/article_embargo'
require 'swagger_client/models/article_embargo_updater'
require 'swagger_client/models/article_update'
require 'swagger_client/models/articles_creator'
require 'swagger_client/models/author'
require 'swagger_client/models/authors_creator'
require 'swagger_client/models/categories_creator'
require 'swagger_client/models/category'
require 'swagger_client/models/collaborator'
require 'swagger_client/models/collection'
require 'swagger_client/models/collection_create'
require 'swagger_client/models/collection_private_link_creator'
require 'swagger_client/models/collection_update'
require 'swagger_client/models/common_search'
require 'swagger_client/models/confidentiality_creator'
require 'swagger_client/models/custom_article_field'
require 'swagger_client/models/error_message'
require 'swagger_client/models/file_creator'
require 'swagger_client/models/group'
require 'swagger_client/models/institution'
require 'swagger_client/models/institution_accounts_search'
require 'swagger_client/models/license'
require 'swagger_client/models/location'
require 'swagger_client/models/private_authors_search'
require 'swagger_client/models/private_link'
require 'swagger_client/models/private_link_creator'
require 'swagger_client/models/project'
require 'swagger_client/models/project_collaborator'
require 'swagger_client/models/project_collaborator_invite'
require 'swagger_client/models/project_create'
require 'swagger_client/models/project_note'
require 'swagger_client/models/project_note_create'
require 'swagger_client/models/project_update'
require 'swagger_client/models/public_file'
require 'swagger_client/models/response_message'
require 'swagger_client/models/role'
require 'swagger_client/models/short_account'
require 'swagger_client/models/upload_file_part'
require 'swagger_client/models/upload_info'
require 'swagger_client/models/user'
require 'swagger_client/models/version'
require 'swagger_client/models/article_search'
require 'swagger_client/models/author_complete'
require 'swagger_client/models/collection_complete'
require 'swagger_client/models/collection_search'
require 'swagger_client/models/private_file'
require 'swagger_client/models/project_article'
require 'swagger_client/models/project_complete'
require 'swagger_client/models/project_note_private'
require 'swagger_client/models/project_private'
require 'swagger_client/models/article_complete'
require 'swagger_client/models/private_article_search'
require 'swagger_client/models/private_collection_search'
require 'swagger_client/models/project_complete_private'
require 'swagger_client/models/article_complete_private'

# APIs
require 'swagger_client/api/articles_api'
require 'swagger_client/api/authors_api'
require 'swagger_client/api/collections_api'
require 'swagger_client/api/institutions_api'
require 'swagger_client/api/other_api'
require 'swagger_client/api/projects_api'

module SwaggerClient
  class << self
    # Customize default settings for the SDK using block.
    #   SwaggerClient.configure do |config|
    #     config.username = "xxx"
    #     config.password = "xxx"
    #   end
    # If no block given, return the default Configuration object.
    def configure
      if block_given?
        yield(Configuration.default)
      else
        Configuration.default
      end
    end
  end
end
