=begin
#Figshare API

#Figshare apiv2. Using Swagger 2.0

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::AccountGroupRolesCreate
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AccountGroupRolesCreate' do
  before do
    # run before each test
    @instance = SwaggerClient::AccountGroupRolesCreate.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AccountGroupRolesCreate' do
    it 'should create an instance of AccountGroupRolesCreate' do
      expect(@instance).to be_instance_of(SwaggerClient::AccountGroupRolesCreate)
    end
  end
end

