=begin
#Figshare API

#Figshare apiv2. Using Swagger 2.0

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::AuthorsCreator
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AuthorsCreator' do
  before do
    # run before each test
    @instance = SwaggerClient::AuthorsCreator.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthorsCreator' do
    it 'should create an instance of AuthorsCreator' do
      expect(@instance).to be_instance_of(SwaggerClient::AuthorsCreator)
    end
  end
  describe 'test attribute "authors"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

