=begin
#Figshare API

#Figshare apiv2. Using Swagger 2.0

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::ProjectCollaboratorInvite
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'ProjectCollaboratorInvite' do
  before do
    # run before each test
    @instance = SwaggerClient::ProjectCollaboratorInvite.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of ProjectCollaboratorInvite' do
    it 'should create an instance of ProjectCollaboratorInvite' do
      expect(@instance).to be_instance_of(SwaggerClient::ProjectCollaboratorInvite)
    end
  end
  describe 'test attribute "role_name"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
       #validator = Petstore::EnumTest::EnumAttributeValidator.new('String', ["viewer", "collaborator"])
       #validator.allowable_values.each do |value|
       #  expect { @instance.role_name = value }.not_to raise_error
       #end
    end
  end

  describe 'test attribute "user_id"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "email"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "comment"' do
    it 'should work' do
       # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end

