=begin
#Figshare API

#Figshare apiv2. Using Swagger 2.0

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'date'

module SwaggerClient

  class InstitutionAccountsSearch
    # Search term
    attr_accessor :search_for

    # Filter by active status
    attr_accessor :is_active

    # Page number. Used for pagination with page_size
    attr_accessor :page

    # The number of results included on a page. Used for pagination with page
    attr_accessor :page_size

    # Number of results included on a page. Used for pagination with query
    attr_accessor :limit

    # Where to start the listing(the offset of the first result). Used for pagination with limit
    attr_accessor :offset

    # filter by institution_user_id
    attr_accessor :institution_user_id

    # filter by email
    attr_accessor :email


    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'search_for' => :'search_for',
        :'is_active' => :'is_active',
        :'page' => :'page',
        :'page_size' => :'page_size',
        :'limit' => :'limit',
        :'offset' => :'offset',
        :'institution_user_id' => :'institution_user_id',
        :'email' => :'email'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'search_for' => :'String',
        :'is_active' => :'Integer',
        :'page' => :'Integer',
        :'page_size' => :'Integer',
        :'limit' => :'Integer',
        :'offset' => :'Integer',
        :'institution_user_id' => :'String',
        :'email' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}){|(k,v), h| h[k.to_sym] = v}

      if attributes.has_key?(:'search_for')
        self.search_for = attributes[:'search_for']
      end

      if attributes.has_key?(:'is_active')
        self.is_active = attributes[:'is_active']
      end

      if attributes.has_key?(:'page')
        self.page = attributes[:'page']
      end

      if attributes.has_key?(:'page_size')
        self.page_size = attributes[:'page_size']
      else
        self.page_size = 10
      end

      if attributes.has_key?(:'limit')
        self.limit = attributes[:'limit']
      end

      if attributes.has_key?(:'offset')
        self.offset = attributes[:'offset']
      end

      if attributes.has_key?(:'institution_user_id')
        self.institution_user_id = attributes[:'institution_user_id']
      end

      if attributes.has_key?(:'email')
        self.email = attributes[:'email']
      end

    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properies with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      if !@is_active.nil? && @is_active > 1
        invalid_properties.push("invalid value for 'is_active', must be smaller than or equal to 1.")
      end

      if !@is_active.nil? && @is_active < 0
        invalid_properties.push("invalid value for 'is_active', must be greater than or equal to 0.")
      end

      if !@page.nil? && @page > 5000
        invalid_properties.push("invalid value for 'page', must be smaller than or equal to 5000.")
      end

      if !@page.nil? && @page < 1
        invalid_properties.push("invalid value for 'page', must be greater than or equal to 1.")
      end

      if !@page_size.nil? && @page_size > 1000
        invalid_properties.push("invalid value for 'page_size', must be smaller than or equal to 1000.")
      end

      if !@page_size.nil? && @page_size < 1
        invalid_properties.push("invalid value for 'page_size', must be greater than or equal to 1.")
      end

      if !@limit.nil? && @limit > 1000
        invalid_properties.push("invalid value for 'limit', must be smaller than or equal to 1000.")
      end

      if !@limit.nil? && @limit < 1
        invalid_properties.push("invalid value for 'limit', must be greater than or equal to 1.")
      end

      if !@offset.nil? && @offset > 5000
        invalid_properties.push("invalid value for 'offset', must be smaller than or equal to 5000.")
      end

      if !@offset.nil? && @offset < 1
        invalid_properties.push("invalid value for 'offset', must be greater than or equal to 1.")
      end

      return invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      return false if !@is_active.nil? && @is_active > 1
      return false if !@is_active.nil? && @is_active < 0
      return false if !@page.nil? && @page > 5000
      return false if !@page.nil? && @page < 1
      return false if !@page_size.nil? && @page_size > 1000
      return false if !@page_size.nil? && @page_size < 1
      return false if !@limit.nil? && @limit > 1000
      return false if !@limit.nil? && @limit < 1
      return false if !@offset.nil? && @offset > 5000
      return false if !@offset.nil? && @offset < 1
      return true
    end

    # Custom attribute writer method with validation
    # @param [Object] is_active Value to be assigned
    def is_active=(is_active)

      if !is_active.nil? && is_active > 1
        fail ArgumentError, "invalid value for 'is_active', must be smaller than or equal to 1."
      end

      if !is_active.nil? && is_active < 0
        fail ArgumentError, "invalid value for 'is_active', must be greater than or equal to 0."
      end

      @is_active = is_active
    end

    # Custom attribute writer method with validation
    # @param [Object] page Value to be assigned
    def page=(page)

      if !page.nil? && page > 5000
        fail ArgumentError, "invalid value for 'page', must be smaller than or equal to 5000."
      end

      if !page.nil? && page < 1
        fail ArgumentError, "invalid value for 'page', must be greater than or equal to 1."
      end

      @page = page
    end

    # Custom attribute writer method with validation
    # @param [Object] page_size Value to be assigned
    def page_size=(page_size)

      if !page_size.nil? && page_size > 1000
        fail ArgumentError, "invalid value for 'page_size', must be smaller than or equal to 1000."
      end

      if !page_size.nil? && page_size < 1
        fail ArgumentError, "invalid value for 'page_size', must be greater than or equal to 1."
      end

      @page_size = page_size
    end

    # Custom attribute writer method with validation
    # @param [Object] limit Value to be assigned
    def limit=(limit)

      if !limit.nil? && limit > 1000
        fail ArgumentError, "invalid value for 'limit', must be smaller than or equal to 1000."
      end

      if !limit.nil? && limit < 1
        fail ArgumentError, "invalid value for 'limit', must be greater than or equal to 1."
      end

      @limit = limit
    end

    # Custom attribute writer method with validation
    # @param [Object] offset Value to be assigned
    def offset=(offset)

      if !offset.nil? && offset > 5000
        fail ArgumentError, "invalid value for 'offset', must be smaller than or equal to 5000."
      end

      if !offset.nil? && offset < 1
        fail ArgumentError, "invalid value for 'offset', must be greater than or equal to 1."
      end

      @offset = offset
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          search_for == o.search_for &&
          is_active == o.is_active &&
          page == o.page &&
          page_size == o.page_size &&
          limit == o.limit &&
          offset == o.offset &&
          institution_user_id == o.institution_user_id &&
          email == o.email
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [search_for, is_active, page, page_size, limit, offset, institution_user_id, email].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map{ |v| _deserialize($1, v) } )
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = SwaggerClient.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map{ |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end

end
