=begin
#Figshare API

#Figshare apiv2. Using Swagger 2.0

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::AuthorsApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'AuthorsApi' do
  before do
    # run before each test
    @instance = SwaggerClient::AuthorsApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of AuthorsApi' do
    it 'should create an instance of AuthorsApi' do
      expect(@instance).to be_instance_of(SwaggerClient::AuthorsApi)
    end
  end

  # unit tests for private_author_details
  # Author details
  # View author details
  # @param author_id Author unique identifier
  # @param [Hash] opts the optional parameters
  # @return [AuthorComplete]
  describe 'private_author_details test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for private_authors_search
  # Search Authors
  # Search for authors
  # @param [Hash] opts the optional parameters
  # @option opts [PrivateAuthorsSearch] :search Search Parameters
  # @return [Array<Author>]
  describe 'private_authors_search test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
