=begin
#Figshare API

#Figshare apiv2. Using Swagger 2.0

OpenAPI spec version: 2.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.2.3

=end

require 'spec_helper'
require 'json'

# Unit tests for SwaggerClient::OtherApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'OtherApi' do
  before do
    # run before each test
    @instance = SwaggerClient::OtherApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of OtherApi' do
    it 'should create an instance of OtherApi' do
      expect(@instance).to be_instance_of(SwaggerClient::OtherApi)
    end
  end

  # unit tests for categories_list
  # Public Categories
  # Returns a list of public categories
  # @param [Hash] opts the optional parameters
  # @return [Array<Category>]
  describe 'categories_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for file_download
  # Public File Download
  # Starts the download of a file
  # @param file_id 
  # @param [Hash] opts the optional parameters
  # @return [nil]
  describe 'file_download test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for licenses_list
  # Public Licenses
  # Returns a list of public licenses
  # @param [Hash] opts the optional parameters
  # @return [Array<License>]
  describe 'licenses_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for private_account
  # Private Account information
  # Account information for token/personal token
  # @param [Hash] opts the optional parameters
  # @return [Account]
  describe 'private_account test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for private_licenses_list
  # Private Account Licenses
  # This is a private endpoint that requires OAuth. It will return a list with figshare public licenses AND licenses defined for account&#39;s institution.
  # @param [Hash] opts the optional parameters
  # @return [Array<License>]
  describe 'private_licenses_list test' do
    it "should work" do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
